# Generated by Django 4.2.27 on 2025-12-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='daily_usage_rate',
            field=models.FloatField(default=0.0, help_text='Average daily consumption (kg/units)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(help_text='Current stock in kg or units'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.FloatField(help_text='Alert when stock drops below this'),
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Stock Added'), ('CONSUME', 'Stock Consumed')], max_length=10)),
                ('quantity_changed', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.inventoryitem')),
            ],
        ),
    ]
